---
- name: Remove Default Host Entry
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1\s+k8s.*$'
    state: absent
  tags:
    - k8s

- name: Ensure Hosts File
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.name }}"
  with_items:
    - { ip: "192.168.1.11", name: "k8s1" }
    - { ip: "192.168.1.12", name: "k8s2" }
    - { ip: "192.168.1.13", name: "k8s3" }
  tags:
    - k8s

- name: Ensure Docker Apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - k8s

- name: Ensure Docker Repository
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
    state: present
    update_cache: yes
  tags:
    - k8s

- name: Ensure Google Cloud Apt Key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  tags:
    - k8s

- name: Ensure Kubernetes Repository
  become: yes
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    update_cache: yes
  tags:
    - k8s

- name: Ensure Base Tools
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - curl
    - jq
    - bc
    - gawk
    - apt-transport-https
  tags:
    - k8s

- name: Update system
  become: yes
  command: "apt-get update -y"
  tags:
    - k8s

- name: List docker-ce versions
  become: yes
  command: "apt-cache madison docker-ce"
  register: dockerce
  tags:
    - k8s
- debug: msg="{{ dockerce.stdout }}"

- name: List docker-ce-cli versions
  become: yes
  command: "apt-cache madison docker-ce-cli"
  register: dockercecli
  tags:
    - k8s
- debug: msg="{{ dockercecli.stdout }}"

- name: List containerd versions
  become: yes
  command: "apt-cache madison containerd.io"
  register: containerd
  tags:
    - k8s
- debug: msg="{{ containerd.stdout }}"

- name: List kubelet versions
  become: yes
  command: "apt-cache madison kubelet"
  register: kubelet
  tags:
    - k8s
- debug: msg="{{ kubelet.stdout }}"

- name: List kubeadm versions
  become: yes
  command: "apt-cache madison kubeadm"
  register: kubeadm
  tags:
    - k8s
- debug: msg="{{ kubeadm.stdout }}"

- name: Ensure Docker
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce=5:20.10.0~3-0~ubuntu-xenial
    - docker-ce-cli=5:20.10.0~3-0~ubuntu-xenial
    - containerd.io
  tags:
    - k8s

- name: Ensure Kubernetes
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet=1.20.0-00
    - kubeadm=1.20.0-00
  tags:
    - k8s

- name: Ensure Docker Group
  group:
    name: docker
    state: present
  tags:
    - k8s

- name: Ensure User in Docker Group
  user:
    name=vagrant
    groups=docker
    append=yes
  tags:
    - k8s

- name: Ensure Kubernetes Cleanup
  become:
  copy:
    src: files/clean-k8s
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
  tags:
    - k8s

- name: Ensure Docker Socat
  become:
  copy:
    src: files/docker-socat
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
  tags:
    - k8s

- name: Ensure swap is off
  become: yes
  command: "swapoff -a"
  tags:
    - k8s

- name: Remove swap from fstab
  become: yes
  lineinfile:
    dest: /etc/fstab
    regexp: 'swap'
    state: absent
  tags:
    - k8s

- name: Create playground directories
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
  with_items:
    - { path: "/var/k8s" }
    - { path: "/var/tmp/kafka/kafka-logs" }
    - { path: "/var/tmp/zookeeper/data" }
    - { path: "/var/tmp/zookeeper/datalog" }
    - { path: "/var/tmp/flink/jobmanager" }
    - { path: "/var/tmp/flink/taskmanager" }
  tags:
    - k8s
