# Default values for flink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: 192.168.56.11:30000/
  repository: nextbreakpoint/flink
  tag: 1.9.0
  pullPolicy: Always

jobmanager:
  resources:
    limits:
     cpu: 100m
     memory: 300Mi
    requests:
     cpu: 100m
     memory: 300Mi
  environment:
    - name: FLINK_JM_HEAP
      value: "256"

taskmanager:
  resources:
    limits:
     cpu: 100m
     memory: 1100Mi
    requests:
     cpu: 100m
     memory: 1100Mi
  environment:
    - name: FLINK_TM_HEAP
      value: "1024"

storage:
  create: true

nodes:
  - "1"
  - "2"
  - "3"
