# Default values for kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: 192.168.56.11:30000/
  repository: nextbreakpoint/cp-kafka
  tag: 5.3.1
  pullPolicy: Always

service:
  firstExternalBrokerPort: 32000
  firstExternalMetricsPort: 32070

resources:
  limits:
   cpu: 100m
   memory: 1100Mi
  requests:
   cpu: 100m
   memory: 1100Mi

environment:
  jvmFlags: "-Xms1024M -Xmx1024M"

secrets:
  password: "test"

nodes:
  - "1"
  - "2"
  - "3"

zookeeper:
  connect: "zookeeper-k8s1:2181,zookeeper-k8s2:2181,zookeeper-k8s3:2181"
