#!/bin/bash

set -e

COMMAND=""

for i in "$@"; do
  case $i in
    --install)
      COMMAND="INSTALL"
      shift
      ;;
    --uninstall)
      COMMAND="UNINSTALL"
      shift
      ;;
    *)
      POSITIONAL_ARGS+=("$1")
      shift
      ;;
  esac
done

if [[ $COMMAND = "INSTALL" ]]; then
  kubectl apply -f /var/k8s/docker-registry.yaml
fi

if [[ $COMMAND = "UNINSTALL" ]]; then
  kubectl delete -f /var/k8s/docker-registry.yaml
fi
