{{- $fullname := include "flink.fullname" . -}}
{{- $name := include "flink.name" . -}}
{{- $chart := include "flink.chart" . -}}
{{- $root := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-jobmanager-headless
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: 8081
      targetPort: ui
      protocol: TCP
      name: ui
    - port: 6123
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    app: {{ $name }}
    release: {{ $root.Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-jobmanager
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
    external: "false"
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: ui
      protocol: TCP
      name: ui
    - port: 6123
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    app: {{ $name }}
    release: {{ $root.Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-jobmanager-external
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
    external: "true"
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 32081
      targetPort: ui
      protocol: TCP
      name: ui
    - port: 6123
      nodePort: 32063
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    app: {{ $name }}
    release: {{ $root.Release.Name }}
