#!/bin/bash

cat <<EOF >/var/tmp/ssl.conf
[req]
distinguished_name = distinguished_name_req
[distinguished_name_req]
[v3_ca]
subjectAltName = IP:192.168.1.10
EOF

openssl req -config /var/tmp/ssl.conf -extensions v3_ca -newkey rsa:4096 -nodes -sha256 -keyout /var/tmp/docker-registry.key -x509 -days 365 -subj "/CN=192.168.1.10" -out /var/tmp/docker-registry.crt

openssl x509  -text -in /var/tmp/docker-registry.crt

docker run --rm --entrypoint htpasswd registry:2 -Bbn test password > /tmp/htpasswd

sudo cp /tmp/htpasswd /var/tmp/docker-registry/auth/htpasswd

sudo mkdir -p /etc/docker/certs.d/192.168.1.10:5000

sudo cp /var/tmp/docker-registry.crt /etc/docker/certs.d/192.168.1.10:5000/ca.crt

cp /var/tmp/docker-registry.crt /vagrant

cp /var/tmp/docker-registry.* /var/tmp/docker-registry/certs

kubectl create -f /var/tmp/docker-registry.yaml
