#!/bin/bash

cat <<EOF >/var/tmp/docker-registry.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pv-claim-k8s1-docker-registry
  labels:
    app: registry
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
      matchLabels:
        app: registry
---
apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
spec:
  containers:
  - name: registry
    image: registry:2
    imagePullPolicy: Always
    ports:
      - containerPort: 5000
    volumeMounts:
      - mountPath: /var/lib/registry
        name: registry-data
  volumes:
    - name: registry-data
      persistentVolumeClaim:
        claimName: local-pv-claim-k8s1-docker-registry
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8s1
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-k8s1-docker-registry
  labels:
    app: registry
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  local:
    path: /var/tmp/docker-registry
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s1
EOF

kubectl create -f /var/tmp/docker-registry.yaml
